### ISSUE TITLE
Material presets

### ISSUE THREAD

**Issue by derwassi** [mossblaser/plottie#5]
One thing about the silhouette studio software I like are the material presets. You just have to select the material, then cut depth, force and speed are automatically selected.

Bringing this feature to plottie would be awesome.
The presets are nicely stored in csv files in silhouette studio in the folder Resources\Resources\SPEC_S\condition*.csv (individually for each of their machines).
Adding own materials (e.g. in a .plotty/materials file) would be a great addition too.

a material could then be used like this:
plottie --material=cardboard test.svg

I would try to do it myself, but my python skills are not that good;-)

**Comment by mossblaser** [comment]
This is something I had wondered about making but was put off by the fact my device didn't have an auto-blade and so the presets table wouldn't be too useful. (That and I found the presets in silhouette studio always needed tweaking anyway). As such I never got around to building such a feature since it wasn't too useful to me.

> I would try to do it myself, but my python skills are not that good;-)

If you wanted to have a crack at it yourself I'm very happy to provide help and/or feedback :). If not I'll probably close this issue for now and offer my apologies for my laziness :).

**Comment by derwassi** [comment]
When i find some time over the next weeks i May give it a Shot, so you can keep it open for a month or two;-)
